### ISSUE TITLE
People API not returning a good error if items is None

### ISSUE THREAD

**Issue by jbogarin** [CiscoDevNet/ciscosparkapi#11]
When I search by displayName or email, if my search is not successful, then the I get an error saying:

> 'items' object not found in JSON data: {'items': []}

However, I believe the library should handle the error with a response like:

> Search returned 0 results

I'm talking about these lines: https://github.com/CiscoDevNet/ciscosparkapi/blob/710aea82b2e227a23372d24c5f98653d32fece63/ciscosparkapi/api/people.py#L141-L144

I'm not sure if you want to handle that kind of events like I'm suggesting. If you want to do it like that, I can help with the code. If not, feel free to close this "issue".

**Comment by cmlccie** [comment]
Yes, we can definitely handle that better, and it shouldn't be difficult to update.  That error check was meant to ensure that when an iterator of items is requested, that the returned JSON data from Spark contained a top-level 'items' object.  Sounds like I just need to put a quick check in for a successful response with no content.  and raise a stop iteration exception.

**Comment by cmlccie** [comment]
Fixed in v0.2.4
