### ISSUE TITLE
Select & Implement an Auto-Documentation Tool

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/ciscosparkapi#17]
Select a tool that leverages the docstrings in the package's code to assist with building a live and complete set of package documentation.

Some [possible tool options are available here](https://wiki.python.org/moin/DocumentationTools).

**Do others have experience or preference with or for any others?**

**Comment by cmlccie** [comment]
Selected [Sphinx](http://www.sphinx-doc.org/en/stable/index.html); working on implementation.

**Comment by DJF3** [comment]
Great news.. Can't wait to see this documentation. Let me know if you want me to test it.

**Comment by cmlccie** [comment]
The user docs are mostly complete...  Check out the recent commits to the `development` branch, your testing and feedback is very welcome.  I hope to finish these up soon an move on to some other items.

**Comment by DJF3** [comment]
Sorry, I can provide feedback on documentation but couldn't really find that in the development branch (apologies, fairly new to github ;-)

**Comment by cmlccie** [comment]
No problem.  They should be published shortly (within the next week).  I appreciate your feedback when you have had a chance to review.

**Comment by cmlccie** [comment]
This one is complete!  😎

We are using Sphinx, and the docs are now available at [ciscosparkapi.readthedocs.io](http://ciscosparkapi.readthedocs.io/en/latest/).  They are automatically updated with every push/pull to master.

Enjoy!  Please raise an issue if you see any errors or opportunities for enhancement in the docs.
