### ISSUE TITLE
'CiscoSparkAPI' object has no attribute 'message'

### ISSUE THREAD

**Issue by DJF3** [CiscoDevNet/ciscosparkapi#22]
When running the script with the demo script from the readme document I see the following error

`  File "sparkapitest.py", line 26, in <module>
    api.message.create(demo_room.id, text="Welcome to the room!", files=["welcome.jpg"])
AttributeError: 'CiscoSparkAPI' object has no attribute 'message'
`

**AttributeError**: 'CiscoSparkAPI' object has **no attribute 'message'**

Used (sudo) PIP to install the library on my Mac.

Is this a known error?

**Comment by DJF3** [comment]
UPDATE:  the example in the README file has 2 errors preventing it from running:
The last line of code: 
`api.message.create(demo_room.id, text="Welcome to the room!", files=["welcome.jpg"])`
**Replace**: api.message.create with api.message**s**.create (note the 's')
**Replace**: "welcome.jpg" with (for example) "https://developer.ciscospark.com/images/logo_spark_lg@256.png"

Then it will run fine!

**Comment by cmlccie** [comment]
@DJF3 , thank you for the feedback on the documentation!  You are correct, and your feedback is very much appreciated.  I will update the doc to correct the typo (missing `s`) and to use a URL that can work for everyone who wants to run the example.  -Thank you!!

**Comment by cmlccie** [comment]
@DJF3 , I have corrected this bug, and released the complete User Documentation @ [ciscosparkapi.readthedocs.io](http://ciscosparkapi.readthedocs.io).

Check it out, and please do submit your feedback on the docs.
