### ISSUE TITLE
webhooks.update fails "TypeError: update() takes exactly 2 arguments (3 given)"

### ISSUE THREAD

**Issue by brbester** [CiscoDevNet/ciscosparkapi#23]
def update(self, webhookId, **update_attributes):

tried packaging with json.dumps and passing that way and still fails.  devleoper.ciscospark.com requires webhook name and targetUrl at minimum....

**Comment by cmlccie** [comment]
@brbester , can you share a code sample that isn't working?  You should be able to pass in the attributes that you want updated as parameters to the update function (that is the purpose of the ``**update_atributes``).

**Comment by brbester** [comment]
Actually the posted example expresses the issue: https://github.com/CiscoDevNet/ciscosparkapi/blob/master/examples/ngrokwebhook.py

``` 
dict=api.webhooks.update(whid, webhookname, targetUrl) #not working yet
```

**Comment by brbester** [comment]
more ways I have tried passing with no luck:  
```
 attributes={}
    attributes["name"]=webhookname
    attributes["targetUrl"]=targetUrl
#    attributes = { "name":webhookname, "targetUrl":targetUrl}
#    attributes = json.dumps(attributes)
#    attributes = '{ "targetUrl":'+targetUrl+'}'
#    attributes = '"targetUrl":'+targetUrl
#    attributes = "targetUrl="+targetUrl
#    attributes= "name=webhookname"

    print attributes
    dict=api.webhooks.update(whid, attributes)

```
by replacing attributes with name=webhookname I was able to get a different error (not at all sure if this passed as a string, a boolean or what, or if the webhookname variable is even resolved to a string)  Needless to say Python kwargs are beyond my skill level/understanding....

```
 File "ngrokwebhook.py", line 85, in <module>
    dict=api.webhooks.update(whid, name=webhookname)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/api/webhooks.py", line 251, in update
    json_obj = self.session.post('webhooks/' + webhookId, json=put_data)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/restsession.py", line 159, in post
    check_response_code(response, erc)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/helper.py", line 66, in check_response_code
    response=response)
ciscosparkapi.exceptions.SparkApiError: Response Code [405] - Unknown Response Code
```
405 isn't defined on the developer page for webhook PUT

**Comment by cmlccie** [comment]
@brbester ,

The syntax for updating a webhook is:

``` python
webhook_obj = api.webhooks.update(whid, name=webhookname, targetUrl=targetUrl)
```

**Comment by brbester** [comment]
@cmlccie Same error:  [Url is a string, webhookname is a string)

Traceback (most recent call last):
  File "ngrokwebhook.py", line 85, in <module>
    dict=api.webhooks.update(whid, targetUrl=Url, name=webhookname)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/api/webhooks.py", line 251, in update
    json_obj = self.session.post('webhooks/' + webhookId, json=put_data)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/restsession.py", line 159, in post
    check_response_code(response, erc)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/helper.py", line 66, in check_response_code
    response=response)
ciscosparkapi.exceptions.SparkApiError: Response Code [405] - Unknown Response Code

**Comment by brbester** [comment]
@cmlccie Hold up - think it may have fixed itself ;-)  apparently was running an older version of the API and just did a pip --upgrade and working fine now.  Thanks!
