### ISSUE TITLE
Character encoding error - SparkApiError does not exist?

### ISSUE THREAD

**Issue by DJF3** [CiscoDevNet/ciscosparkapi#24]
When listing all the rooms of a user it stops at 
**room name**: "Domás"
When replacing all accents in the room.title it processes the above room but stops at:
**room name**:  "Rob Ørnebånd"

So I tried to use the example from the Readme.md file, using the try-except:
```
except SparkApiError as e:
    print(e)
```
Error message: "SparkApiError undefined" or something similar. 

Question:
**#1 .. How to deal with strange characters in room names?** 
       (I just ran into room names starting with an emoticon)

**#2 .. How to handle errors?** (or see what happened when requesting a room list?)

Python: 3.5
Listing the rooms works perfectly when running the script from the command line instead of using CGI.

**Comment by DJF3** [comment]
BTW, fantastic library !! Job well done.

**Comment by cmlccie** [comment]
@DJF3 , hmm... This is an interesting one.  I pretty regularly working with room names that have special characters (mostly emoticons in my case).  Can you share the full 'Exception' output when you are seeing iteration stop at these items?

You are handling errors correctly.  Catching ``SparkApiError`` s should show you any errors returned by the Cisco Spark cloud.  Note: The exception objects contain the full request and response objects that were involved in the API call, which you can examine from an interactive Python prompt to get additional visibility into what went wrong.

**Comment by DJF3** [comment]
Weather tried locally (macbook) or using a hosting provider:
```
#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
# coding=utf-8
import os
from ciscosparkapi import CiscoSparkAPI

os.environ['SPARK_ACCESS_TOKEN'] = 'xyzxyz'
api = CiscoSparkAPI()
try:
    message = api.messages.create('123098123098123098123098123', text='message_text')
    print("New message created, with ID:", message.id)
    print(message.text)
except SparkApiError as e:
    print(e)
```

There's no difference when using _pass_ instead of _print(e)_

**Generates an error message:**
_Traceback (most recent call last):
  File "sparkapitest-message.py", line 14, in <module>
    except SparkApiError as e:
NameError: name 'SparkApiError' is not defined_

This should absolutely generate an error as both the access token and the room id are wrong.
DJ

**Comment by cmlccie** [comment]
...you are correct.  It definitely should (and is) generating an exception.  To catch a custom / package exception, you have to import that exception into your namespace.  You are just missing ``SparkApiError`` from your ``from ciscosparkapi import ...`` statement.

Your code should look like this:
``` python
#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
# coding=utf-8
import os
from ciscosparkapi import CiscoSparkAPI, SparkApiError

os.environ['SPARK_ACCESS_TOKEN'] = 'xyzxyz'
api = CiscoSparkAPI()
try:
    message = api.messages.create('123098123098123098123098123', text='message_text')
    print("New message created, with ID:", message.id)
    print(message.text)
except SparkApiError as e:
    print(e)
```

Which runs and does indeed catch the exception(s) and print them when they are fired.
