### ISSUE TITLE
Enhancement request: Docs: include returned fields

### ISSUE THREAD

**Issue by DJF3** [CiscoDevNet/ciscosparkapi#29]
Hi,
It would be nice if the documentation would list which fields are returned.
Example: Memberships: http://ciscosparkapi.readthedocs.io/en/latest/user/api.html#memberships

> Returns:	
> When iterated, the GeneratorContainer, yields
> the memberships returned from the Cisco Spark query.

Nice would be the format that's used for the _Parameters_ section , looking a bit like this
> Returns:	
> When iterated, the GeneratorContainer, yields
> the memberships returned from the Cisco Spark query.
> - id
> - roomId
> - personId
> - personEmail
> - isModerator
> - isMonitor
> - created

Or like this:

> - id, roomId, personId, personEmail, isModerator, isMonitor, created

**Comment by cmlccie** [comment]
Thank you DJF3, I actually have this item (updating the docstrings, which is where this information comes from) already logged as an issue #16 , and it is making its way up the backlog as I have been getting some items knocked out.  🙂

The returned SparkDataObjects (and their contents) are documented in the API docs.  I will work to clean these up and link the specifically returned data objects to the docs of the methods that return them.

I'm going to flag this as a duplicate, as this work will get done as part of issue #16 .
