### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/ciscosparkapi#3]
some example will help newcomers start with the sdk,

don't need a lot to start with

**Comment by cmlccie** [comment]
Completely agreed.  It's on the backlog.  Care to write or contribute here?

**Comment by ObjectIsAdvantag** [comment]
Would love but I am not very versed on python.
It is much easier for me to review python code than write some.

**Comment by cmlccie** [comment]
Some examples have been provided (thank you @brbester !).

More are always welcome!

_Potential Contributors:_  Feel free to submit a pull request if you have examples you would like to share.  **Note that the package now supports Python v2 and v3.**  It is preferred if your example scripts support both as well.  -Thank you!
