### ISSUE TITLE
team_membership update is using wrong method

### ISSUE THREAD

**Issue by ciscomonkey** [CiscoDevNet/ciscosparkapi#30]
CiscoSparkAPI.team_memberships.update() is using the wrong method.  Should be using put instead of post

in teammemberships.py, line 239 should be changed from:
        json_obj = self._session.post('team/memberships/' + membershipId,
to:
        json_obj = self._session.put('team/memberships/' + membershipId,

**Comment by cmlccie** [comment]
Thank you @ciscomonkey !  I did catch this with the new test suite I am working to complete, but I haven't pushed the commits to master yet.  I will get this done soon and publish a patched release.

**Comment by cmlccie** [comment]
I have fixed this bug, and an associated bug in the memberships.update() method.  Thank you for reporting it!

The automated test suite is nearly done, but I figured I should go ahead and release this...  No need to wait for the automated testing.
