### ISSUE TITLE
Unable to Update Teams

### ISSUE THREAD

**Issue by Deepar3292** [CiscoDevNet/ciscosparkapi#39]
Update Team API returning 405 response code due to the "POST" method used instead of "PUT"

**Comment by cmlccie** [comment]
@Deepar3292 , you are spot on.  Don't know how we missed this one.  I'll merge your pull request and push a package update shortly.

**Comment by cmlccie** [comment]
@Deepar3292 this issue has been fixed by merging your PR and pushing `v0.6.2`.  Please let us know if you have any further issues.  Your feedback and PRs are always welcome.

_-Thank You!_
