### ISSUE TITLE
Add new API Query Parameters and Spark object Attributes

### ISSUE THREAD

**Issue by gj0nyg** [CiscoDevNet/ciscosparkapi#44]
api.people.list should allow orgId to be passed as a valid parameter to allow partner admins to scan customer orgs. Other calls may also need to be updated but I haven't checked.

**Comment by cmlccie** [comment]
@gj0nyg Thank you for raising this.  I have checked and there are some new query parameters and object attributes.  @jbogarin has already submitted a provisional pull request #45 for this parameter.  I will see if I can go through and update the packages params and object attributes towards the end of this week / over the weekend.

**Comment by cmlccie** [comment]
I'm broadening this issue to encompass the quick update that is needed to add support for the new query parameters and object attributes that have been added to the APIs and their responses.

**Comment by cmlccie** [comment]
Resolved via PR #47 

@gj0nyg Thank you for raising this issue!  @jbogarin Thank you for your pull request and thoughts, your commits and work were merged in.  

Let me know if you experience any issues with the updates.  I have thoroughly tested everything, so hopefully you shouldn't... 🤞 😎

_-Thank you!!_
