### ISSUE TITLE
Versioner Value

### ISSUE THREAD

**Issue by marksull** [CiscoDevNet/ciscosparkapi#5]
Just as an opportunity to provide feedback based on my experience with your previous cmlCiscoSparkSDK package was that versioneer was an unnecessary hurdle. The versioneer version determination would fail (0_unknown) or die depending on how I tried to install the package and the Py/Pip version being used. To be honest I had more issues installing that package due to versioneer than I had using the package. The value of using versioneer for what I expect will be a low touch package doesn't seem warranted IMHO if you want users to experience an easy an simple intro to Spark.

The versioneer issues I am referring to are documented here (https://github.com/warner/python-versioneer) under the section known limitations. 

My AU$0.02!

**Comment by cmlccie** [comment]
Thank you marksull for the feedback!

Question for you... Were you trying to build a package or just install the package?  Versioneer shouldn't be a requirement for installing / using the package.  I use it (being lazy) only to save me the trouble of having to manually update version numbers.  With Versioneer I can just set git tags and then use setup.py to create a new distribution file.

Let me know what you are running into here.  I haven't had any issues with it, but if it is causing problems, I can always remove it and do things manually.

**Comment by marksull** [comment]
It is simply an installation issue. This quote is taken from the Versioner git page:

"Versioneer will look for .git in parent directories, and most operations should get the right version string. **However pip and setuptools have bugs and implementation details which frequently cause pip install . from a subproject directory to fail to find a correct version string (so it usually defaults to 0+unknown).

pip install --editable . should work correctly. setup.py install might work too.**"

The point I was simply trying to make is; does the value that versioneer brings justify its inclusion? I would say yes if this was a high touch package with lots of contributors, but if you are only going to do a few updates a year I would suggest maybe just manually set the version ;-)

It's just a suggestion, not a requirement. Feel free to disregard if you want to continue to use versioneer. Maybe I have simple been unlucky.

FWIW, I tested ciscosparkapi on 3.5.2 and 2.7.12 with the default pip and found it installed fine without having to use the versioneer workaround (pip install --editable .). 

Below is another example of an installation failure of the cmlCiscoSparkSDK package due to versioneer.

```
(play-3-5-2) MARKSULL-M-41T1:py3 marksull$ git clone 
https://github.com/cmlccie/cmlCiscoSparkSDK.git
Cloning into 'cmlCiscoSparkSDK'...
remote: Counting objects: 111, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 111 (delta 4), reused 0 (delta 0), pack-reused 98
Receiving objects: 100% (111/111), 44.30 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.

** Lets install as we normally would **

(play-3-5-2) MARKSULL-M-41T1:py3 marksull$ cd cmlCiscoSparkSDK/
(play-3-5-2) MARKSULL-M-41T1:cmlCiscoSparkSDK marksull$ pip install .

Processing /Users/marksull/Development/Python/py3/cmlCiscoSparkSDK
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages/requests-2.7.0-py3.5.egg (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Requirement already satisfied (use --upgrade to upgrade): pytz in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Requirement already satisfied (use --upgrade to upgrade): future in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Installing collected packages: cmlCiscoSparkSDK
  Running setup.py install for cmlCiscoSparkSDK ... error
    Complete output from command /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/jg/355kf3c9219693tz5y0gr4sh0000gn/T/pip-siys42br-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jg/355kf3c9219693tz5y0gr4sh0000gn/T/pip-s68mzvai-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/include/site/python3.5/cmlCiscoSparkSDK:
    /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing 'v1.1+6.g033d05a' to '1.1+6.g033d05a'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/cmlCiscoSparkSDK
    copying cmlCiscoSparkSDK/__init__.py -> build/lib/cmlCiscoSparkSDK
    copying cmlCiscoSparkSDK/_version.py -> build/lib/cmlCiscoSparkSDK
    copying cmlCiscoSparkSDK/jsondata.py -> build/lib/cmlCiscoSparkSDK
    copying cmlCiscoSparkSDK/restapi.py -> build/lib/cmlCiscoSparkSDK
    copying cmlCiscoSparkSDK/sparkapi.py -> build/lib/cmlCiscoSparkSDK
    UPDATING build/lib/None
    error: [Errno 2] No such file or directory: 'build/lib/None'
    
    ----------------------------------------
Command "/Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/jg/355kf3c9219693tz5y0gr4sh0000gn/T/pip-siys42br-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jg/355kf3c9219693tz5y0gr4sh0000gn/T/pip-s68mzvai-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/include/site/python3.5/cmlCiscoSparkSDK" failed with error code 1 in /var/folders/jg/355kf3c9219693tz5y0gr4sh0000gn/T/pip-siys42br-build/

** Lets install using the workaround suggested by versioneer **

(play-3-5-2) MARKSULL-M-41T1:cmlCiscoSparkSDK marksull$ pip install --editable .
Obtaining file:///Users/marksull/Development/Python/py3/cmlCiscoSparkSDK
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages/requests-2.7.0-py3.5.egg (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Requirement already satisfied (use --upgrade to upgrade): pytz in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Requirement already satisfied (use --upgrade to upgrade): future in /Users/marksull/.anyenv/envs/pyenv/versions/3.5.2/envs/play-3-5-2/lib/python3.5/site-packages (from cmlCiscoSparkSDK==1.1+6.g033d05a)
Installing collected packages: cmlCiscoSparkSDK
  Running setup.py develop for cmlCiscoSparkSDK
Successfully installed cmlCiscoSparkSDK
```

**Comment by marksull** [comment]
oops, sorry clicked close ;-)

**Comment by cmlccie** [comment]
Gotcha.  I see what you are saying.  I haven't had any issues with it, and it should only affect those packaging and posting the distributions (which is just me right now).

Please test installing it from pip, and if you experience any issues, please let me know.

With this automation, the build process is very easy for me:
```
$ git tag v0.1.1
$ python setup.py sdist
$ twine upload dist/*
```

...so it is worth it to me.  If it causes issues, I don't have any problem removing the automation and managing the version numbers manually.

One of the big benefits to me is how Versioneer automatically automatically generates version numbers for builds in-between releases.  I can generate test builds and they will always have unique and identifiable version numbers.
