### ISSUE TITLE
Error during installation and setup - 

### ISSUE THREAD

**Issue by Pracheta16** [CiscoDevNet/ciscosparkapi#54]
While installing ciscosparkapi, faced the following error during installation - 
Have attached the full error as shown below. 

Collecting ciscosparkapi
  Using cached ciscosparkapi-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/volatile/tmp/pip-build-mL2umY/ciscosparkapi/setup.py", line 62, in <module>
        packages=find_packages(include=['ciscosparkapi', 'ciscosparkapi.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'

Command "python setup.py egg_info" failed with error code 1 in /var/volatile/tmp/pip-build-mL2umY/ciscosparkapi/

Please let me know if there is something obvious that I'm missing...

**Comment by cmlccie** [comment]
Hi @Pracheta16 , can you confirm what interpreter (CPython, etc.) and what version of Python you are using?  Also, which process are you using to install it (`pip` or Git download + `setup.py install`)?

**Comment by Pracheta16** [comment]
Hi, I was trying to run this using guestshell in IOS XE, python2.7.5, and was also using pip. Although, I tried both (pip and Git + setup.py install), got the same error.
Is it possible that because I don't have direct internet access (accessing internet through a proxy, and my mgmt intf is in a vrf) that this could happen?
